apiVersion: v1
kind: Pod
metadata:
  name: file-test
  namespace: rook
spec:
  containers:
  - name: file-test1
    image: dangula/rook-integration
    imagePullPolicy: IfNotPresent
    env:
    - name : TestName
      value: INSERT_TEST_TYPE
    volumeMounts:
    - mountPath: "/tmp/rookfs"
      name: testfs
  volumes:
  - name: testfs
    cephfs:
      monitors: INSERT_HERE
      user: admin
      secretRef:
        name: rook-admin
      readOnly: false
  restartPolicy: Never

